export const LOAD_USERS_START = 'LOAD_USERS_START';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL';
export const SET_USERS_ORDER = 'SET_USERS_ORDER';
export const SET_USERS_GROUPING = 'SET_USERS_GROUPING';
export const ADD_USER = 'ADD_USER';
